import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div style={{ display: "flex" }}>
        <Suspense>
          <Sidebar />
        </Suspense>
        <div className={inter.className} style={{height: '100%', width:'100%'}}>{children}</div>
      </div>
    </>
  );
}
